name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */5 * * *"  # Every 5 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure this matches your bot's requirements

    # Step 3: Update package lists (necessary for installing packages)
    - name: Update package lists
      run: sudo apt-get update

    # Step 4: Install ffmpeg if necessary
    - name: Install ffmpeg (optional)
      run: sudo apt-get install -y ffmpeg --fix-missing
      if: ${{ secrets.INSTALL_FFMPEG == 'true' }}  # Condition to install if needed

    # Step 5: Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 6: Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true  # To help debug dependency issues if any

    # Step 7: Run the bot with the Discord token from secrets
    - name: Run bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: python main.py  # Replace with the correct entry point of your bot
      continue-on-error: true  # Optional: Continue workflow if bot run fails

    # Optional: Notify on failure
    - name: Notify on failure
      if: failure()
      run: echo "Bot deployment failed. Please check the logs."
