name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */5 * * *"  # Every 5 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure this matches your bot's requirements

    - name: Update package lists
      run: sudo apt-get update

    - name: Install ffmpeg (optional)
      run: sudo apt-get install -y ffmpeg --fix-missing
      if: needs-ffmpeg # Add a condition to avoid installing if not needed

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: python main.py  # Replace with the correct entry point of your bot

      # Optional: Add error handling (example)
      # continue-on-error: true  # This allows the workflow to continue even if this step fails
