name: Deploy Discord Bot
on:
  push:
    branches:
      - main  # Adjust to your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This step ensures your code is checked out
        
      - name: Install FFmpeg  # Ensure FFmpeg is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg 
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run the bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: python main.py
